"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DATABASE_POOL_URL = exports.APP_BASE_URL = exports.GMAIL_EMAIL = exports.GMAIL_APP_PASS = exports.SECRET_KEY = exports.DIRECT_URL = exports.DATABASE_URL = exports.CLOUDINARY_CLOUD_NAME = exports.CLOUDINARY_API_SECRET = exports.CLOUDINARY_API_KEY = exports.PORT = void 0;
var PORT = Number(process.env.PORT) || "8000";
exports.PORT = PORT;
var CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY || "";
exports.CLOUDINARY_API_KEY = CLOUDINARY_API_KEY;
var CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET || "";
exports.CLOUDINARY_API_SECRET = CLOUDINARY_API_SECRET;
var CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME || "";
exports.CLOUDINARY_CLOUD_NAME = CLOUDINARY_CLOUD_NAME;
var DATABASE_URL = process.env.DATABASE_URL || "";
exports.DATABASE_URL = DATABASE_URL;
var DIRECT_URL = process.env.DIRECT_URL || "";
exports.DIRECT_URL = DIRECT_URL;
var SECRET_KEY = process.env.SECRET_KEY || "";
exports.SECRET_KEY = SECRET_KEY;
var GMAIL_EMAIL = process.env.GMAIL_EMAIL || "";
exports.GMAIL_EMAIL = GMAIL_EMAIL;
var GMAIL_APP_PASS = process.env.GMAIL_APP_PASS || "";
exports.GMAIL_APP_PASS = GMAIL_APP_PASS;
var APP_BASE_URL = process.env.APP_BASE_URL || "";
exports.APP_BASE_URL = APP_BASE_URL;
var DATABASE_POOL_URL = process.env.DATABASE_POOL_URL || "";
exports.DATABASE_POOL_URL = DATABASE_POOL_URL;
